version: 2

updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/Toronto"
    target-branch: 'main'
    reviewers:
      - anarian